# Generated by Django 4.1.4 on 2023-02-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0002_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
