# Generated by Django 4.1.4 on 2023-02-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0003_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=200)),
                ('file_student', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
