# Generated by Django 4.1.4 on 2023-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0004_student_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='file_student',
            field=models.FileField(null=True, upload_to='document_form/'),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='file_student',
            field=models.FileField(upload_to='documents_modelform/'),
        ),
    ]
