# Generated by Django 4.1.7 on 2023-02-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0006_alter_student_file_student_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Model',
            new_name='StudentModel',
        ),
    ]
