# Generated by Django 4.1.7 on 2023-02-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0007_rename_student_model_studentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='file_student',
            field=models.FileField(upload_to='uploadfile/StudentModel/documents'),
        ),
    ]
