# Generated by Django 4.1.7 on 2023-02-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='image_file',
            new_name='imagefile',
        ),
    ]
