# Generated by Django 4.1.7 on 2023-02-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0002_rename_image_file_uploadimage_imagefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='imagefile',
            new_name='image_file',
        ),
    ]
