# Generated by Django 4.1.7 on 2023-03-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0003_rename_imagefile_uploadimage_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image_file',
            field=models.ImageField(upload_to='uploadimage/UploadImage/images/'),
        ),
    ]
