# Generated by Django 4.1.7 on 2023-02-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
