# Generated by Django 4.1.7 on 2023-02-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_product_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type_id',
            new_name='type',
        ),
    ]
