# Generated by Django 4.1.7 on 2023-02-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0003_rename_type_id_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type_book',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_book',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
