# Generated by Django 4.1.7 on 2023-02-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0008_alter_category_picture_alter_product_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='sales',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ManyToManyField(to='Catalog.category'),
        ),
    ]
