# Generated by Django 4.1.7 on 2023-03-02 07:20

import User.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=User.models.AddressField(null=True),
        ),
    ]
